image: ruby:2.7

pages:
  stage: build
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
    - run ARCH= && dpkgArch="$(dpkg --print-architecture)" \
      && case "${dpkgArch##*-}" in \
        amd64) ARCH='x64';; \
        ppc64el) ARCH='ppc64le';; \
        s390x) ARCH='s390x';; \
        arm64) ARCH='arm64';; \
        armhf) ARCH='armv7l';; \
        i386) ARCH='x86';;
    - apt install curl
      && curl -fsSLO --compressed "https://nodejs.org/dist/v12.21.0/node-v12.21.0-linux-$ARCH.tar.xz" \
      && tar -xJf "node-v12.21.0-linux-$ARCH.tar.xz" -C /usr/local
      && rm "node-v12.21.0-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
      && ln -s /usr/local/bin/node /usr/local/bin/nodejs \

  artifacts:
    paths:
      - public

build-job:
  stage: build
  script:
    - echo "Welcome on board !"

test-fields:
  stage: test
  script:
    - echo "Checking Rocket setup properties..."
    - sh test-fields.sh

test-format:
  stage: test
  script:
    - echo "Checking values format..."
    # - sleep 20

test-consistency:
  stage: test
  script:
    - echo "Checking data consistency..."
    # - sleep 30

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys the code from the $CI_COMMIT_BRANCH branch."
    - echo "Rocket has been launched !"