image: ruby:2.7

pages:
  stage: build
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public

build-job:
  stage: build
  script:
    - echo "Welcome on board !"

test-fields:
  stage: test
  script:
    - echo "Checking Rocket setup properties..."

test-format:
  stage: test
  script:
    - echo "Checking values format..."
    - sleep 20

test-consistency:
  stage: test
  script:
    - echo "Checking data consistency"
    - sleep 30

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys the code from the $CI_COMMIT_BRANCH branch."
    - echo "Rocket has been launched !"