# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

version: 2
jobs:
  build:
    docker:
      - image: node:12-buster

        steps:
          - run:
              name: The First Step
              command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

