# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: node:12-buster
  test:
    steps:
     - run:
          name: The First Step
          command: |
              echo "Welcome on board !"
     - run:
          name: test-fields
          command:
               echo "Checking Rocket setup properties..."
               sh test-fields.sh
     - run:
          name: test-format
          command:
               echo "Checking values format..."
     - run:  
          name: test-consistency
          command:
               echo "Checking data consistency..."
          
          
